// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnoxakazjgvtevpbacqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indub3hha2F6amd2dGV2cGJhY3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NjU1NjIsImV4cCI6MjA2NDI0MTU2Mn0.oOotnz-kOgf7VvViGSDMB1Bc8SzZ03ZzIB28TCtj5Ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);